// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL080r9MSdtCk3NmN5tYBkLRglphaykEQ',
    appId: '1:303925910082:android:bf14196d3c3b66b5ecebdb',
    messagingSenderId: '303925910082',
    projectId: 'quizme-59b1e',
    storageBucket: 'quizme-59b1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpCVBKJprxgHNnlLSCKq0XuJ40DhmvK4U',
    appId: '1:303925910082:ios:51daa9e4b62c3993ecebdb',
    messagingSenderId: '303925910082',
    projectId: 'quizme-59b1e',
    storageBucket: 'quizme-59b1e.appspot.com',
    iosClientId: '303925910082-4fup5n38hhuhsl8aqnvibbo5eejfqquh.apps.googleusercontent.com',
    iosBundleId: 'com.dev-vlad.quizme',
  );
}
